baseURL = "https://epistolae.ctl.columbia.edu/"
copyright = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)"
googleAnalytics = "UA-311226-23"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Epistolae"
SectionPagesMenu = "main"
theme = "ctl-epistolae"

[blackfriday]
  fractions = false

[params]
    description = "Epistolae is a collection of letters to and from women in the Middle Ages, from the 4th to the 13th century. The letters, written in Latin, are linked to the names of the women involved, with English translations and, where available, biographical sketches of the women and some description of the subject matter or the historic context of the letter."
    keywords = "women literature"
    shortTitle = "Epistolae"
